### ISSUE TITLE
Be flexible with installation directory

### ISSUE THREAD

**Issue by mjklemm** [ROCm-Developer-Tools/og#5]
It seems like that the installation script is rather inflexible when trying to install the build into a different folder than the home folder.  Please introduce a OG_INSTALL_PREFIX=... envirable that can point to anywhere in the file system and then installs the usual filesystem tree, e.g., $OG_INSTALL_PREFIX/{bin,share,lib}

**Comment by mjklemm** [comment]
I guess the difference between `OGDIR` and `OG_INSTALL_PREFIX` should be that `OGDIR` points to a temporary build directory, while `OG_INSTALL_PREFIX` should be pointing to what's used for the individual components' configure scripts to install when running `make install`.

**Comment by ThorBl** [comment]
Issue is resolved. PR #6 has been merged.
